### ISSUE TITLE
Busybox and posix shell support

### ISSUE THREAD

**Issue by albertony** [sakai135/wsl-vpnkit#10]
Great work, very useful!

Is it an idea to make it a tiny bit more "generic" so that it can run, for example, in an Alpine distro with default shell?

I have been working on a version which seems close:

https://github.com/sakai135/wsl-vpnkit/compare/main...albertony:busybox

Most of it is quite straight forward changes I think, but the trap/cleanup logic is a bit hard to get right. When first making the script valid `#! /bin/sh` I kept getting two `vpnkit-tap-vsockd` left after exit (Ctrl+C) - when running from Alpine's sh, but also Debian's sh. This never happens when running with bash, in fact I could even remove the existing `kill $PID_RELAY $PID_TAP` and it seems to always stop all the the subshells/processes on exit! The only way to make it kill the vpnkit-tap-vsockd was to add a `kill 0` at the end of the close function, which I guess is a bit dirty?

**Comment by sakai135** [comment]
Thanks, and sorry for my late response. 

`kill 0` does do the job for cleaning up, so I'm good with merging your current changes if you want to make a PR.
