### ISSUE TITLE
Check if service wsl-vpnkit is already running

### ISSUE THREAD

**Issue by SalahELGO** [sakai135/wsl-vpnkit#100]
Hello,

I want to check as I start my distro (debian) if wsl-vpnkit service is up. So I added a script at my .login:

```if [[ ! -v WSL_KIT ]]; then
  read "wsl_vpnkit_yn? * Do you want to start wsl-vpnkit ? y/n "
  echo

  if [[ "$wsl_vpnkit_yn" =~ ^[Yy]$ ]]; then
    echo "Start wsl-vpnkit ..."
    wsl.exe -d wsl-vpnkit service wsl-vpnkit start
  fi
fi
```

Is there anyway to obtain the information and put it in the "WSL_KIT" variable ?

**Comment by sakai135** [comment]
You can do something like `wsl.exe -d wsl-vpnkit ps | grep wsl-vm` to check if the process is running.

**Comment by SalahELGO** [comment]
It worked, thank you so much !

**Comment by F21** [comment]
For those looking to start the `wsl-vpnkit` service quietly if it has not been started yet every time you open a new wsl terminal, I added this to the top of my `.zshrc`. You can also add it to your `.bashrc` or `.profile` depending on what shell you're using.

```bash
if [[ -z $(wsl.exe -d wsl-vpnkit ps | grep wsl-vm) ]]; then
    wsl.exe -d wsl-vpnkit service wsl-vpnkit start
fi
```
