### ISSUE TITLE
how to start from another distro?

### ISSUE THREAD

**Issue by riezebosch** [sakai135/wsl-vpnkit#101]
> Start wsl-vpnkit from your other WSL 2 distros. Add the command to your .profile or .bashrc to start wsl-vpnkit when you open your WSL terminal.
>
> wsl.exe -d wsl-vpnkit service wsl-vpnkit start

How do you start wsl-vpnkit from other distros?

**Comment by sakai135** [comment]
You should be able to start it by running `wsl.exe -d wsl-vpnkit service wsl-vpnkit start` from your normal distro unless Windows interop is disabled.

**Comment by riezebosch** [comment]
Thank you! I tried it without the extension and it sure then failed.
