### ISSUE TITLE
Using wsl-vpnkit behind corporate proxy.

### ISSUE THREAD

**Issue by lrk** [sakai135/wsl-vpnkit#103]
Hi,

is there a way to configure wsl-vpnkit to use a corporate proxy ? 

wget, used in checks fail because it cannot get a website outside of my corporate network.

I saw a PR about `HTTP_PROXY_CONFIG_PATH` (#76) but i assume it was related to docker's vpnkit.

My current workaround is to configure `CHECK_HOST` to use a domain inside my corporate network.

Best regards.

**Comment by sakai135** [comment]
With v0.2.x, you can take advantage of VPNKit's built-in support for HTTP proxy.

Otherwise, you can configure the environment variables `http_proxy` and the like in your WSL 2 distro.

**Comment by jbockle** [comment]
with v0.3 it seems I had to configure both http_proxy and https_proxy environment variables, apt also required some additional configuration
