### ISSUE TITLE
How to install with no internet from WSL 2

### ISSUE THREAD

**Issue by ballardt** [sakai135/wsl-vpnkit#11]
The instructions in the README seem to use `apt` to install packages from within WSL 2, but, as far as I understand, the purpose of the software is to provide internet access to the VM. In my case, for example, I cannot use `apt` as it is listed in the README commands, even with Docker Desktop for Windows installed, as it fails to resolve the request to the package repository.

Am I missing something, or does this software require a functioning `apt get` to work? Thanks, if I could get it working this would be extremely helpful for several people on my team. In any case, I am thinking I may be able to download the packages manually and install with dpkg.

**Comment by albertony** [comment]
No you are not missing something... unless I am missing something too! :)

But I did this: Located download links for individual package files on my host computer and downloaded them from a browser (or rather, a PowerShell script), then used the package tool in wsl in "offline-mode" to install the packages from file, by referencing them in the /mnt/c/etc. path back where they are on the host. Needs the package socat, but then it needs some dependencies that are also missing so there are a couple more.

Debian:
- The official image being on "stretch" still, I needed the following:
https://packages.debian.org/stretch/amd64/libwrap0/download
https://packages.debian.org/stretch/amd64/libssl1.1/download
https://packages.debian.org/stretch/amd64/socat/download
- Just download the files and then from wsl refer to the files by path. Example (not the actual file names, don't know if order is important, but I did dependencies first and socat last):
`apt-get install libwrap0.deb libssl1.1.deb socat.deb`

Ubuntu 20.04:
- Only missing socat package. Download url can be retrieved by the folowing command in wsl: `apt-get install socat --print-uris -qq`. Then download this link on host etc, and install it just like with Debian.

Alpine:
- Tested the official "Minimal root filesystem" distribution from alpinelinux.org, so not actually a WSL distribution at all, but works like a charm. Except, needs bash to run the wsl-vpnkit script.
- Downloads from https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/x86_64/
- Packages needed: ncurses-terminfo-base, ncurses-libs, readline, socat, bash
- Install with `apk add --quiet --repositories-file /dev/null <packagefiles>...`.

**Comment by ballardt** [comment]
@albertony This did indeed work for me, thank you!

**Comment by sakai135** [comment]
Thanks for the detailed steps, @albertony. The steps in the README were intended for when you have access to the internet within WSL2 but no access when connected to the VPN, since that was the situation I had. I'll try to update the README sometime soon to incorporate this where you don't have internet access at all within WSL2.

**Comment by andyneff** [comment]
Another option is to convert the WSL to WSL1, install packages, and convert it back to WSL2

- `wsl --set-version {distro_name} 1`
- `wsl --set-version {distro_name} 2`
