### ISSUE TITLE
wsl-gvproxy.exe is malicious for mc afee

### ISSUE THREAD

**Issue by mounirabid** [sakai135/wsl-vpnkit#123]
wsl-gvproxy.exe is considered malicious by mc afee. And it is blocked when I start a wsl distribution.
Do you have any solution ?
![image](https://user-images.githubusercontent.com/71446014/164392505-f23b06d4-cd3a-459a-a6bf-62f605c1c541.png)

**Comment by sakai135** [comment]
There isn't much I can do to evade security solutions. You could try an older version.

**Comment by mounirabid** [comment]
Works with v0.2.5

**Comment by pierre2113** [comment]
as user mounirabid suggested i tried v0.2.5, it works without issue.
v0.2.5 doesn't copy file wsl-gvproxy.exe,   it  copies 2 other files without a .exe file extension
maybe that helps avoiding quarantine.   2 other files are  npiprerelay, and wsl-vpnkit.
