### ISSUE TITLE
Problem with juniper vpn

### ISSUE THREAD

**Issue by tomece** [sakai135/wsl-vpnkit#127]
Hello,
my behaviour with vpnkit:

vpn off:
dns is working
wsl2 has internet connection
wsl2 has (of course) no connection to corp. intranet

vpn on:
dns is working
wsl2 lost partial internet connection: ping is possible, all other connections will timeout
wsl2 has connection to corp.intranet

My question: can I somehow route only corp intranet traffic (whole x.x.x.x/8 network) through vpn and leave the rest as it is without vpn ?

**Comment by sakai135** [comment]
@tomece You can do that by editing the calls to `ip route` in the wsl-vpnkit script. 

Another reason might be that your VPN requires you to use a proxy to access the public internet. If so, you will have to configure that manually inside your WSL 2 distro.
