### ISSUE TITLE
windows11,when I close the cmd or powershell window It's not work

### ISSUE THREAD

**Issue by shuohao** [sakai135/wsl-vpnkit#129]
wsl.exe -d wsl-vpnkit service wsl-vpnkit start

**Comment by sakai135** [comment]
Try running the command `wsl.exe -d wsl-vpnkit service wsl-vpnkit start` from within your WSL 2 distro instead of cmd or powershell.

**Comment by shuohao** [comment]
> Try running the command `wsl.exe -d wsl-vpnkit service wsl-vpnkit start` from within your WSL 2 distro instead of cmd or powershell.

![image](https://user-images.githubusercontent.com/4637107/169958799-01be3c6d-7a83-4e55-af11-cc3b51097bd3.png)

**Comment by sakai135** [comment]
@shuohao When you run `explorer.exe .` from that terminal within WSL 2, does it open properly?

**Comment by shuohao** [comment]
> @shuohao When you run `explorer.exe .` from that terminal within WSL 2, does it open properly?

yes. open propely
![image](https://user-images.githubusercontent.com/4637107/170067817-9e048606-7b28-4143-8264-b3695552ca3e.png)

**Comment by shuohao** [comment]
It may be related to the operating system version。 windows 11 22H2 home not work, but windows 11 21H2 business worked well

**Comment by sakai135** [comment]
Glad it's working for one of your machines, although it should work for Home too.

The `.` at the end in the command `explorer.exe .` was important since I wanted to see if your Windows Explorer can open your home dir inside your WSL 2 distro.

![image](https://user-images.githubusercontent.com/1585689/170810308-7fc26aff-a2dd-4350-a1cd-85200af18a9c.png)

**Comment by shuohao** [comment]
> Glad it's working for one of your machines, although it should work for Home too.
> 
> The `.` at the end in the command `explorer.exe .` was important since I wanted to see if your Windows Explorer can open your home dir inside your WSL 2 distro.
> 
> ![image](https://user-images.githubusercontent.com/1585689/170810308-7fc26aff-a2dd-4350-a1cd-85200af18a9c.png)

Sorry, I reinstalled the system..   windows 11 professional  edition
