### ISSUE TITLE
Reliability and Issues running in parallel with Docker Desktop

### ISSUE THREAD

**Issue by jamesdboone** [sakai135/wsl-vpnkit#13]
The current script is a great, educational example on how one can use vnpkit to use WSL2 in a VPN environment.

I ended up making a number of adjustments to the script to:
a) If the script is executed again, kill all lingering processes from last run both on windows and linux side, as currently it would start to stack processes and wouldn't work right.

#pre-cleanup any running processes
echo "Cleaning up anything left running..."
PROCS=("socat" "vpnkit-tap-vsockd")
for value in "${PROCS[@]}"
do
  while pidof $value; do
    echo "Killing ${value}...$(pidof $value)"
    kill $(pidof $value)
  done
done

b) Look up the vpnkit parent id before killing to ensure I'm not killing an active 'docker desktop' instance of vpnkit.

cleanup_vpnkit() {
  PIDS="$(${POWERSHELL_PATH} -Command "(Get-Process \"vpnkit\").Id")"
  echo "PIDS: $PIDS"
  mypids=( $(echo "$PIDS" | fmt -999) )
  for i in "${mypids[@]}"; do
    PID="$(echo "$i" | tr -d '\n' | tr -d '\r')"
    PARENT="$(${POWERSHELL_PATH} -Command "(Get-Process -Id ((gwmi win32_process |? processid -eq $PID).parentprocessid)).ProcessName" | tr -d '\n\r')"
    echo "Parent: '$PARENT'"
    if [ ! "$PARENT" = "Docker Desktop" ]; then
      echo "Delete it!"
      ${POWERSHELL_PATH} -Command "Stop-Process -Id $PID"
    else
      echo "Keep it!"
    fi
  done
}

Lastly, I wrapped the script with something that runs it in a tmux and pipes output to a log file, then I run that via wsl cli in the background (windows batch script):

#!/bin/bash
#---start go script

if [ ! "$(id -u)" = "0" ]; then
  echo "Not root, calling self as root..."
  sudo -E sh -c "$0"
  exit "$?"
else
  echo "Running as root..."
fi
#first graceful kill
if ps -ef | grep -v grep | grep "/bin/sh ./wsl-vpnkit" >/dev/null; then
  echo "Graceful kill of older processes..."
  for i in $(ps -ef | grep "/bin/sh ./wsl-vpnkit" | grep -v grep | awk '{print $2}'); do kill $i; done
fi

if ps -ef | grep -v grep | grep "/bin/sh ./wsl-vpnkit" >/dev/null; then
  echo "Wait 60 sec for graceful death..."
  sleep 60
fi

if ps -ef | grep -v grep | grep "/bin/sh ./wsl-vpnkit" >/dev/null; then
  echo "Not so graceful kill of older processes..."
  for i in $(ps -ef | grep "/bin/sh ./wsl-vpnkit" | grep -v grep | awk '{print $2}'); do kill -9 $i; done
fi

#startup
echo "Starting up..."

cd /opt/wsl-vpnkit
if [ -f "./wsl-vpnkit.out" ]; then
  mv ./wsl-vpnkit.out ./wsl-vpnkit.out.$(date +'%Y%m%d%H%M%S')
fi

tmux new -d './wsl-vpnkit > ./wsl-vpnkit.out 2>&1'
#---end go script

The windows batch script contents:
wsl -d <my_wsl_distribution> /opt/wsl-vpnkit/go &

This seems to be working pretty reliably for me, so I wanted to share.

I do hope Microsoft either includes a solution like this, or otherwise identifies an alternative solution to make WSL2 work cleanly in VPN environments.  Until then, this is working nicely!

**Comment by jamesdboone** [comment]
One last note on this.  I'm still left with docker-desktop killing all vpnkit instances (including my wsl-vpnkit instance), I don't have a workaround for that.  But with the above solution, I can just re-run my batch script and I'll be back up and running in no time.

**Comment by jamesdboone** [comment]
It looks like simply copying 'vpnkit.exe' to something different, i.e. 'wsl-vpnkit.exe' and calling that in the script resolves docker desktop stomping on it.

**Comment by sakai135** [comment]
Thanks, and it's great to hear that you've found the script useful. I'll see about addressing the points you raised in a future PR.

**Comment by sakai135** [comment]
@jamesdboone I've incorporated some of your script with #15 and #19.
