### ISSUE TITLE
start-stop-daemon: wsl-vpnkit is already running

### ISSUE THREAD

**Issue by Beinish** [sakai135/wsl-vpnkit#133]
Hello,
This post is not about something not working properly, I think tool works perfectly, but there's one thing that annoys me a little.

I added `wsl.exe -d wsl-vpnkit service wsl-vpnkit start` to my `.zshrc` file, and every time I load my shell I get a message `start-stop-daemon: wsl-vpnkit is already running`. I know it's not an issue or anything, but I was wondering what workaround there is to hide this message.

I thought it would be possible to right a simple `if` statement to check whether this service is running or now, but I wasn't sure how to do it.

Any help would be appreciated :)

**Comment by sakai135** [comment]
You can try something like in #100

**Comment by Beinish** [comment]
> You can try something like in #100

Worked! I used
```
if [[ -z $(wsl.exe -d wsl-vpnkit ps | grep wsl-vm) ]]; then
    wsl.exe -d wsl-vpnkit service wsl-vpnkit start
fi
```

Thank you
