### ISSUE TITLE
Can I route traffic in my WSL through a tunnel?

### ISSUE THREAD

**Issue by Beinish** [sakai135/wsl-vpnkit#135]
I would like to route all traffic in my WSL to a specific domain through a tunnel. So basically any `*.domain.com` would go through the tunnel.

I thought this `.ssh/config` file would do the job, but I guess I'm missing something:
```
Host JumpHost
    HostName jumpHost.domain.com
    User username
    IdentityFile ~/.ssh/id_rsa

Host *.domain.com
    ProxyJump JumpHost
    User username
    IdentityFile ~/.ssh/id_rsa
```

Maybe I'm missing something else?
I'm working with Cisco AnyConnect, running the wsl-vpnkit every time I open my terminal.

Any help would be appreciated :)

**Comment by sakai135** [comment]
What do you mean by "all traffic"? Your SSH config is for SSH. If you want to send other requests like HTTP requests through your JumpHost host, you will need to configure your apps.
