### ISSUE TITLE
Configure VS Code Remote WSL Extension -- Unable to find function to change

### ISSUE THREAD

**Issue by jdnordy** [sakai135/wsl-vpnkit#14]
### Expected Behavior
Expect vscode to be able to open in wsl2 while connected to VPN.

Also, tried to follow steps to configure vs code remote extension, but cannot find the necessary function to change.
`async function P(e,t,s){if(l.isWSL1(s))return"127.0.0.1";}`

### Current Behavior
Vscode cannot establish a remote connection to wsl2 when connected to VPN.

### Possible Solution
Work around, turn off vpn, connect to wsl2 with vscode, turn on vpn.

Possible reason for not being able to find the function is I'm using a new version of vscode remote wsl extensions:
`~/.vscode/extensions/ms-vscode-remote.remote-wsl-0.54.6/dist/wslDaemon.js`

### Context (Environment)
wsl: 2
Windows 10: 19042.928
VS Code Remote WSL Extension: 0.54.6

### Notes
Any help is appreciated!

**Comment by sakai135** [comment]
Thanks for the notice. VS Code 1.54 introduced a nice new setting that lets you configure the remote extension to use `::1`. I've updated the README with the information about the new setting. You can read more about it on their release notes linked below.

https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_54.md#fix-for-wsl-2-connection-issues-when-behind-a-proxy
