### ISSUE TITLE
wsasend errors

### ISSUE THREAD

**Issue by 573** [sakai135/wsl-vpnkit#155]
The log of a nonetheless succeeding vpnkit running is flooded by messages of the likes of:

>time="2022-09-14T09:48:12+02:00" level=error msg="Can't proxy a datagram to udp: write udp 192.168.X.X:port->192.168.XX.255:port: wsasend: Ein ungültiges Argument wurde angegeben.\n"

Is there a reason to be concerned ?

**Comment by sakai135** [comment]
Do you have anything running in WSL that would generate UDP traffic?

I wouldn't be concerned about it other than the log file getting large.

**Comment by 573** [comment]
@sakai135 I suspect from a tcpdump run, that it might be my syncthing service, thanks for the pointer !
