### ISSUE TITLE
DNS Suffix Support

### ISSUE THREAD

**Issue by mmadson** [sakai135/wsl-vpnkit#158]
Hi there!

Fantastic utility you have here, really appreciate the hard work. I was wondering if there were any plans to support dns suffixes in a future release? My VPN configures a bunch of default DNS suffixes for our internal network that ideally should be reflected in the /etc/resolv.conf file using the search command. 

If this is already a capability, perhaps I'm running into a bug.

Appreciate your support!

**Comment by sakai135** [comment]
There's no automatic configuration for this right now. You can configure this by setting `generateResolvConf` in `wsl.conf` to `false` and editing your `resolv.conf` manually.

https://learn.microsoft.com/en-us/windows/wsl/wsl-config#network-settings
