### ISSUE TITLE
Only start if needed: wsl-vpnkit status not working

### ISSUE THREAD

**Issue by STiAT** [sakai135/wsl-vpnkit#160]
First of all thank you, this made it possible to reliably use WSL2 via VPN.

To the issue:
In your documentation, you say we could only start the service if required (or not already running).

```
wsl.exe -d wsl-vpnkit service wsl-vpnkit status >/dev/null || \
  wsl.exe -d wsl-vpnkit service wsl-vpnkit start
```

The issue is, that wsl-vpnkit in the 0.3.4 release seems to be missing the status option:
![grafik](https://user-images.githubusercontent.com/1781015/198560559-6de3168a-7200-4558-8f87-c49676b5dd11.png)

Therefore the command fails and it always tries to start the service anyway.

**Comment by STiAT** [comment]
Update: Seems the docs refer to a feature implemented after the release. Probably should only be there after it was released ;-).

**Comment by josesa-xx** [comment]
I've added that to the documentation after changing the init scripts (https://github.com/sakai135/wsl-vpnkit/pull/147), however this will only become effective when there is a new release published.

Alternatively you can build it from source.

**Comment by sakai135** [comment]
@STiAT @josesa-xx thanks, v0.3.5 is out as a pre-release now. I'll mark it as release after a few days of use.

**Comment by sakai135** [comment]
v0.3.8 should resolve this issue.
