### ISSUE TITLE
server certificate verification fails only with vpnkit on

### ISSUE THREAD

**Issue by CornJojk** [sakai135/wsl-vpnkit#170]
Thanks for working on this. It is a great idea, but I haven't been able to get it working. It looks like an error with the way the alpine distro handles certificates? 

Using WSL Ubuntu-20.04, on Windows 10.0.19045
Same issue with VPN on or off (Any connect VPN, version 4.10.xxx)
Same issue with wsl-vpnkit versions 0.2.5 or 0.3.4
DNSmasq is on.
using git fetch command. 

Here are the commands in sequence:

successful `git-fetch` in WSL
```
(base) username@xxx:~/repos/myRepo$ git fetch
(base) username@xxx:~/repos/myRepo$
```

Turn on wsl-vpnkit in powershell:
```
PS C:\Users\username> wsl.exe -d wsl-vpnkit --cd /app service wsl-vpnkit start
PS C:\Users\username>
```

**failed** `git-fetch` in WSL
```
(base) username@xxx:~/repos/myRepo$ git fetch
fatal: unable to access 'https://github.enterprise.domain/myOrg/myRepo.git/': server certificate verification failed. CAfile: none CRLfile: none
(base) username@xxx:~/repos/myRepo$
```

logs from wsl-vpnkit in powershell (showing certificate error again):
```
PS C:\Users\username> wsl.exe -d wsl-vpnkit tail -f /var/log/wsl-vpnkit.log
check: ✔️ nslookup success for example.com AAAA using 192.168.b.1
check: ✔️ nslookup success for example.com AAAA using 192.168.b.1
check: ✔️ nslookup success for example.com AAAA using 172.c.d.1
check: ✔️ nslookup success for example.com AAAA using 1.1.1.1
ping: bad address 'example.com'
check: ➖ ping fail to IPv6 external host (example.com)
140535715105608:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1919:
ssl_client: SSL_connect
wget: error getting response: Connection reset by peer
check: ❌ wget fail for https://example.com
```
Note: the log command does not terminate, does not return the command prompt. If it's user error, then any insights would be appreciated. All the advice I've found says to make changes within the WSL distro (which would be wsl-vpnkit). I can't do that because the distro only gives a "Press [enter] to continue" prompt (as expected).

**Comment by CornJojk** [comment]
Update: Later I discovered my windows machine is having certificate issues from the Anaconda prompt or Git-Bash shells. So I'll troubleshoot that and report back.

**Comment by CornJojk** [comment]
It looks related to this issue (I have cisco anyconnect):
[https://github.com/sakai135/wsl-vpnkit/issues/132](https://github.com/sakai135/wsl-vpnkit/issues/132)

Here is where the other user left off:
VPN ON, and wsl-vpnkit running:
WSL terminal:
```
(base) username@xxx:~/repos/myRepo$ dig @8.8.8.8 www.uol.com.br

; <<>> DiG 9.16.1-Ubuntu <<>> @8.8.8.8 www.uol.com.br
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36355
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.uol.com.br.                        IN      A

;; ANSWER SECTION:
www.uol.com.br.         58      IN      CNAME   dftex7xfha8fh.cloudfront.net.
dftex7xfha8fh.cloudfront.net. 60 IN     A       13.249.85.17
dftex7xfha8fh.cloudfront.net. 60 IN     A       13.249.85.89
dftex7xfha8fh.cloudfront.net. 60 IN     A       13.249.85.88
dftex7xfha8fh.cloudfront.net. 60 IN     A       13.249.85.57

;; Query time: 70 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Nov 29 12:19:33 CST 2022
;; MSG SIZE  rcvd: 149

(base) username@xxx:~/repos/myRepo$ ping 200.147.3.157
PING 200.147.3.157 (200.147.3.157) 56(84) bytes of data.
64 bytes from 200.147.3.157: icmp_seq=1 ttl=64 time=0.750 ms
64 bytes from 200.147.3.157: icmp_seq=2 ttl=64 time=0.749 ms
64 bytes from 200.147.3.157: icmp_seq=3 ttl=64 time=0.645 ms
^C
--- 200.147.3.157 ping statistics ---
16 packets transmitted, 16 received, 0% packet loss, time 15406ms
rtt min/avg/max/mdev = 0.513/0.927/3.059/0.564 ms
(base) username@xxx:~/repos/myRepo$ ping www.uol.com.br
PING dftex7xfha8fh.cloudfront.net (13.249.85.17) 56(84) bytes of data.
64 bytes from server-13-249-85-17.ord52.r.cloudfront.net (13.249.85.17): icmp_seq=1 ttl=64 time=0.661 ms
64 bytes from server-13-249-85-17.ord52.r.cloudfront.net (13.249.85.17): icmp_seq=2 ttl=64 time=0.736 ms
64 bytes from server-13-249-85-17.ord52.r.cloudfront.net (13.249.85.17): icmp_seq=3 ttl=64 time=0.768 ms
^C
--- dftex7xfha8fh.cloudfront.net ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5201ms
rtt min/avg/max/mdev = 0.661/0.755/0.812/0.049 ms
(base) username@xxx:~/repos/myRepo$ 
```

**Comment by sakai135** [comment]
The wsl-vpnkit distro only handles setting up some networking between the WSL2 VM and the Windows host. Any cert validation aside from those explicitly done within the wsl-vpnkit distro will be done on your Ubuntu distro. 

From the `wget fail for https://example.com`, my guess would be that your IT department has some kind of MITM proxy going on. On your Windows host, go to `https://example.com` and verify the certificate. If the cert is an internal one, you will have to configure your WSL distro (Ubuntu-20.04) with that cert.

**Comment by damianj** [comment]
FWIW I was experiencing similar symptoms and it turned out to be as @sakai135 suggested. After adding my companies root certificate, I was no longer getting the certificate validation errors.

**Comment by CornJojk** [comment]
@damianj @sakai135 
Thanks again for working on this. I am still waiting on help from my IT about proxy settings, but I was able to copy the company certs to my WSL distro by following this process:
https://github.com/microsoft/WSL/issues/3161#issuecomment-898007915
I also made a helper script see below.

There are some weird errors related to proxy and authentication, but I think it's working as intended. I'm definitely able to access the internet through the VPN now!

```
#!/bin/bash
for filename in //home/MyUsername/tempCertsFolder/*.cer; do
    for ((i=0; i<=3; i++)); do
        name=${filename##*/}
        basename=${name%.cer}
        newfilename="/usr/local/share/ca-certificates/$(basename "$filename" .cer).crt"
        sudo openssl x509 -inform PEM -in "$filename" -out "$newfilename"
    done
done
```

**Comment by sakai135** [comment]
Thanks @damianj @CornJojk. I'll close the issue since you seem to have figured the issue out.
