### ISSUE TITLE
Usage of import commands and powershell command prevents cross-compile

### ISSUE THREAD

**Issue by gbraad** [sakai135/wsl-vpnkit#171]
In `./build.sh` there is a reliance on:

https://github.com/sakai135/wsl-vpnkit/blob/a074e1c480f18ec1f21b7a28835c91192d14334b/build.sh#L6

and 

https://github.com/sakai135/wsl-vpnkit/blob/a074e1c480f18ec1f21b7a28835c91192d14334b/build.sh#L17-L20

to determine and run specific Windows settings and commands.

**Comment by gbraad** [comment]
Would it be possible to break this up, or perhaps adopt a Makefile that can be used on a automated pipeline?

**Comment by josesa-xx** [comment]
Actually since build.sh is meant to be run inside WSL, line 6 could just be replaced with:
`USERPROFILE=$(wslvar USERPROFILE)`

**Comment by gbraad** [comment]
The `build.sh` serves two purposes. one of them is the actual build that happens in the Docker container, the other is the import into the WSL environment. Several things can be improved:

  * container runtime independent; as I run builds on Podman
  * add a `Makefile`; use `make` to perform the build
  * and the `build.sh` doing a rebuild invoking `make` and the unregister and import

**Comment by josesa-xx** [comment]
I've made some changes to my current pull request https://github.com/sakai135/wsl-vpnkit/pull/169 to split build and import into different scripts and also allow build with `podman` as alternative.

**Comment by gbraad** [comment]
Thanks, I'll check it out

**Comment by gbraad** [comment]
@josesa-xx for `gvisor-tap-vsock` we are adding a systemd service instead as it is more robust.
For our podman-machine implementation we are already using a systemd patch, so with the newer release of 22H2 this is fixed for future setups.

**Comment by sakai135** [comment]
I'll close this issue since #169 seems to resolve the issue.
