### ISSUE TITLE
Questions regarding project lifecycle

### ISSUE THREAD

**Issue by EvertonSA** [sakai135/wsl-vpnkit#177]
Hello greatings,

thanks a lot for this project, this is the solution to use rancher-desktop behind corporate VPN. 

Will this project stay under @sakai135 user or is it planned to be migrated under an organization structure?

Reasons I ask is: is going to be very hard to convince corporate security people this is a must have to use rancher-desktop.

Thanks a lot for the project

**Comment by sakai135** [comment]
Current plan is to eventually upstream at least the main parts.

https://github.com/containers/gvisor-tap-vsock/issues/139

**Comment by gbraad** [comment]
Hi @EvertonSA, I and @sakai135 have spoken about this a while back but got delayed a little as I got ill. We have the idea to upstream most if not all parts to the actual containers group.

**Comment by EvertonSA** [comment]
thanks a lot for the answer I appreciate a lot
