### ISSUE TITLE
Fails to start [cannot connect to host...]

### ISSUE THREAD

**Issue by manojchandrashekar** [sakai135/wsl-vpnkit#178]
I updated to the latest WSL and vpnkit fails to start.

`wsl.exe -d wsl-vpnkit --cd /app tail -f /var/log/wsl-vpnkit.log`:

```
ip: RTNETLINK answers: File exists
ip: RTNETLINK answers: File exists
restored WSL 2 ip route
wsl-gvproxy.exe exists at /wsl-vpnkit/wsl-gvproxy.exe
starting gvproxy at /wsl-vpnkit/wsl-gvproxy.exe...
started gvproxy
waiting for dhcp...
time="2023-01-05T09:41:36Z" level=fatal msg="cannot connect to host: fork/exec /wsl-vpnkit/wsl-gvproxy.exe: no such file or directory"
sh: can't kill pid 61: No such process
wsl-vm exited
```

`wsl.exe --version`:

```
WSL version: 1.0.3.0
Kernel version: 5.15.79.1
WSLg version: 1.0.47
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2364
```

Not sure if I am doing something wrong. Any ideas?

**Comment by sakai135** [comment]
Did you edit the path for `wsl-gvproxy.exe`? With the default configuration, it should be copied to a folder inside your Windows user directory and should show something like `/mnt/c/Users/username/wsl-vpnkit/wsl-gvproxy.exe`.

**Comment by josesa-xx** [comment]
can you please indicate which version of wsl-vpnkit are you running?

You can get it with:
`echo | wsl.exe -d wsl-vpnkit --cd /app | grep "wsl-vpnkit v"`

**Comment by manojchandrashekar** [comment]
Thanks for the support @sakai135 and @josesa-xx. I uninstalled and reinstalled WSL and Ubuntu. (It had gone through 2 major Windows updates and both times I had lost and restored the installation from vdx.)

So, I did not trust the installation anymore. After the fresh install vpnkit works as expected. :)

Thank you!
