### ISSUE TITLE
Can not start wsl-vpnkit

### ISSUE THREAD

**Issue by kenrbnsn** [sakai135/wsl-vpnkit#184]
I downloaded the latest release.

Following the directions, this step works:
`wsl --import wsl-vpnkit --version 2 $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz`
But this step
`wsl -d wsl-vpnkit`
Gives me the following error:
`The operation timed out because a response was not received from the virtual machine or container.
Error code: Wsl/Service/CreateInstance/HCS_E_CONNECTION_TIMEOUT`

**Comment by sakai135** [comment]
Can you try `wsl.exe --shutdown` and try again? Are you able to run your normal WSL distro?

**Comment by kenrbnsn** [comment]
`wsl.exe --shutdown` never came back. All wsl commands after that just hung. A normal WSL distro works fine.

**Comment by kenrbnsn** [comment]
Killing the WSL task using this command from an admin window worked
`taskkill /f /im wslservice.exe`
After the task restarted, wsl-vpnkit seemed to start OK.
