### ISSUE TITLE
Issues with suffix search order and lost connections

### ISSUE THREAD

**Issue by diehard2** [sakai135/wsl-vpnkit#190]
Hi, wsl-vpnkit is working pretty well. However, my connection will stop working after several hours or a VPN reconnect (GlobalProtect 6.0.3-38). Additionally I don't have domain suffix search. Not sure if there's any way to make this more seamless in wsl-vpnkit, but maybe this will help other people if it can't be built in.

``` 
#!/bin/bash

myarray=( $( /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0//powershell.exe -Command "Get-DnsClientServerAddress -AddressFamily ipv4 | Select-Object -ExpandProperty ServerAddresses") )

mysuffixlist=$(/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command "(Get-DnsClientGlobalSetting | Select-Object -ExpandProperty SuffixSearchList) -join ' '")

echo "search ${mysuffixlist}" > /mnt/wsl/resolv.conf

for i in "${myarray[@]}"
do
    :
    echo "nameserver $i" >> /etc/resolv.conf
done

dos2unix /mnt/wsl/resolv.conf
```
Note that it has to be run as root

**Comment by sakai135** [comment]
@diehard2 Could you take a look at the wsl-vpnkit log files and see if there are any info related to it not working on a VPN reconnect?

The domain suffix search is an issue with normal WSL2 as well, which you can follow at https://github.com/microsoft/WSL/issues/701.
