### ISSUE TITLE
Useless command in README.md for systemd

### ISSUE THREAD

**Issue by francisoud** [sakai135/wsl-vpnkit#198]
Hi,

Thanks for this project 💯 

About v0.4.0 documentation: https://github.com/sakai135/wsl-vpnkit/blob/f1826fa489fa844580d6fe8443897b17fbf4c2d4/README.md#setup-systemd [f1826fa]

The command describe in the README.md
`sudo cp ./wsl-vpnkit.service /etc/systemd/system/`

is useless since the `/etc/systemd/system/wsl-vpnkit.service` was created inthe previous command:

    # wsl-vpnkit setup as a distro
    wsl.exe -d wsl-vpnkit --cd /app cat /app/wsl-vpnkit.service | sudo tee /etc/systemd/system/wsl-vpnkit.service

Also this commmand, is not really clear
`sudo nano /etc/systemd/system/wsl-vpnkit.service`

I suppose you wanted to say that people should uncomment/comment this wsl-vpnkit.service part depending on there installation 'way':

    sudo cat /etc/systemd/system/wsl-vpnkit.service
    
    [Service]
    # for wsl-vpnkit setup as a distro
    ExecStart=/mnt/c/Windows/system32/wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit
    
    # for wsl-vpnkit setup as a standalone script
    #ExecStart=/full/path/to/wsl-vpnkit
    #Environment=VMEXEC_PATH=/full/path/to/wsl-vm GVPROXY_PATH=/full/path/to/wsl-gvproxy.exe

I can provide a patch depending on your feedback :)

**Comment by sakai135** [comment]
Hi @francisoud,

Thanks for the feedback. I intended the comment here to apply to the 2 following commands in the group. These lines are for users that had setup wsl-vpnkit as a standalone script.

```
# copy and edit for wsl-vpnkit setup as a standalone script
sudo cp ./wsl-vpnkit.service /etc/systemd/system/
sudo nano /etc/systemd/system/wsl-vpnkit.service
```

What do you propose for making the documentation clearer?

**Comment by jpambrun** [comment]
I used to start the previous version with within the wsl distro I used.
``` 
wsl.exe -d wsl-vpnkit service wsl-vpnkit start
```

Now the documentation seems to request this distro to have systemd which is not always (often even?) the case.
 
What is the recommended way to start it from wsl have it run in the background at all times without systemd?

**Comment by francisoud** [comment]
perfect
