### ISSUE TITLE
What is the recommended way to have it run in the background without systemd?

### ISSUE THREAD

**Issue by sakai135** [sakai135/wsl-vpnkit#199]
I used to start the previous version with within the wsl distro I used.
``` 
wsl.exe -d wsl-vpnkit service wsl-vpnkit start
```

Now the documentation seems to require this distro to have systemd which is not always (often even?) the case.
 
What is the recommended way to start it from wsl have it run in the background at all times without systemd?

_Originally posted by @jpambrun in https://github.com/sakai135/wsl-vpnkit/issues/198#issuecomment-1485655044_

**Comment by sakai135** [comment]
@jpambrun I moved your comment to a new topic.

I chose to switch wsl-vpnkit to use systemd since that is the only way to run background tasks in WSL2 that is actually supported by Microsoft.

You can use the command `wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit` to run wsl-vpnkit in the foreground with other methods to run background tasks such as `start-stop-daemon` similar to the [service script from v0.3](https://github.com/sakai135/wsl-vpnkit/blob/v0.3.x/distro/scripts/wsl-vpnkit.service) or as a [Windows service](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-service?view=powershell-7.2).

**Comment by jpambrun** [comment]
I understand that we are now expected to run from the systemd from one of our other distro. But I find it a lot more cumbersome as mine aren't setup with systemd.

In the previous iteration I would use `service` from the wsl-vpnkit distribution to keep vpnkit up in the background with the command line above. This felt simpler and more complete.
