### ISSUE TITLE
Occur service not found error

### ISSUE THREAD

**Issue by y-vectorfield** [sakai135/wsl-vpnkit#200]
When I started wsl-vpnkit, the service not found error occured.
Following is the real error message.

```bash
$ wsl.exe -d wsl-vpnkit --cd /app service wsl-vpnkit start
/bin/ash: service: not found
```

**Comment by sakai135** [comment]
This has changed between v0.3 and v0.4. If you updated to v0.4, please read the readme to setup the service with systemd if desired.

**Comment by sakai135** [comment]
I have updated the release notes for v0.4.0 to highlight the change.
