### ISSUE TITLE
Setup instructions for Setup systemd doesn't work

### ISSUE THREAD

**Issue by ftimurs** [sakai135/wsl-vpnkit#211]
Copy in pasting the first command in Command Prompt or Powershell results in this error:

`wsl.exe -d wsl-vpnkit --cd /app cat /app/wsl-vpnkit.service | sudo tee /etc/systemd/system/wsl-vpnkit.service`

`'sudo' is not recognized as an internal or external command,`

**Comment by tjhoo** [comment]
I have the same issue too.
In addition, do we need to ensure systemd starts up on boot by updating `/etc/wsl.conf`?
```
[boot]
systemd = true
```
See [Systemd support is now available in WSL!](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/)

**Comment by josesa-xx** [comment]
To enable "systemd" inside a specific distro, all you have to do is this:

```
# activate systemd
sudo git config -f /etc/wsl.conf boot.systemd "true"
 
# need restart to activate
wsl.exe --shutdown
```

Do it in the distro you are working on like Ubuntu or something else other than "wsl-vpnkit".
I don't recommend doing this in the wsl-vpnkit distro though as that is currently working fine without systemd.

if you have a "sudo" error... how about installing "sudo" package or check system PATH ?

**Comment by tjhoo** [comment]
I try to inspect the `wsl-vpnkit` distribution like this,
```
$ wsl.exe -d wsl-vpnkit
C-PF3EKVLL:~# whoami
root
# ls /app/wsl-vpnkit.service
/app/wsl-vpnkit.service
C-PF3EKVLL:~# ls /etc/systemd/
ls: /etc/systemd/: No such file or directory
C-PF3EKVLL:~#
```
The default user is `root` and maybe `sudo` is not required?
Also note that here is no `/etc/systemd` directory.

**Comment by josesa-xx** [comment]
You are missing the point... you are running commands to go inside the distro "wsl-vpnkit" (`wsl.exe -d wsl-vpnkit`) and you shouldn't. That's not the place you want to check if 'sudo' is available or not.

You can see the distros you have available with `wsl.exe -l -v`

**Comment by sakai135** [comment]
Closing since the issue seems resolved. Thanks @josesa-xx.
