### ISSUE TITLE
All v.0.3 releases are corrupted

### ISSUE THREAD

**Issue by SylvainMartel** [sakai135/wsl-vpnkit#213]
We can't use v 0.4 here(our wsl do not seem to support systemd,, probably missing a KB on windows 10.  corporate environment) so we tried to revert back to v0.3 and simply update to the latest version of 0.3,, only to notice that all v0.3 tar.gz packagtes are corrupted on github and won't open, so trying to import them in wsl fails.  I noticed that all those packaged have a virustotal scan, is it possible it was corrupted by that?

**Comment by sakai135** [comment]
@SylvainMartel Can you verify that the hash of your downloaded files match the hash provided on the releases?

**Comment by SylvainMartel** [comment]
They are opening fine now... Hmmm, this happened while at work, and on 2 different computers, mine and the laptop of a colleague.  I'll have to retry from work, but obviously, we can close this issue :P
