### ISSUE TITLE
Clarification on instructions for systemd

### ISSUE THREAD

**Issue by dpanici** [sakai135/wsl-vpnkit#223]
Hi,

I am trying to follow the instructions to setup systemd, in the instructions in the box in the README it says 
```
# copy and edit for wsl-vpnkit setup as a standalone script
sudo cp ./wsl-vpnkit.service /etc/systemd/system/
sudo nano /etc/systemd/system/wsl-vpnkit.service
```

what exactly does this mean? does it mean to uncomment the standalone script parts and comment the setup as a distro part, so that the final file contents look like this?
```
[Unit]
Description=wsl-vpnkit
After=network.target

[Service]
# for wsl-vpnkit setup as a distro
#ExecStart=/mnt/c/Windows/system32/wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit

# for wsl-vpnkit setup as a standalone script
ExecStart=/full/path/to/wsl-vpnkit
Environment=VMEXEC_PATH=/full/path/to/wsl-vm GVPROXY_PATH=/full/path/to/wsl-gvproxy.exe

Restart=always
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

**Comment by Diagano** [comment]
Hi,
Altough I have not attempted this method (went with the systemd service but as a distro) I think the use case would be something like the following:
1. Follow the standalone orders (without running)
2. Copy and edit the wsl-vpnkit.service file. Yes edit to disable the distro option and open the two lines that says "for wsl-vpnkit setup as a standalone script".
3. Please note the **/full/path/to/**wsl-vm and **/full/path/to/**wsl-gvproxy.exe that need to be filled out according to where you run  the standalone install steps.
4. Continue to enable the service\start and check the status of the service

Hope this helps.

**Comment by dpanici** [comment]
Wait, so are the first two blocks either/or? as in

if I did it as a distro, use the first command
```
# wsl-vpnkit setup as a distro
wsl.exe -d wsl-vpnkit --cd /app cat /app/wsl-vpnkit.service | sudo tee /etc/systemd/system/wsl-vpnkit.service
```
And if I did it as a standalone, use the second set of instructions?
```
# copy and edit for wsl-vpnkit setup as a standalone script
sudo cp ./wsl-vpnkit.service /etc/systemd/system/
sudo nano /etc/systemd/system/wsl-vpnkit.service
```

**Comment by Diagano** [comment]
As far as I see, yes.
I have tried both methods by now and both worked for me. That is the 
- distro, with systemd service 
- standalone script with systemd service (I tend to prefer this one, because there are no external dependecies or configuration steps if I export the image and import in a different system)

Again, please note that if you go with the standalone script way after the "installation" installed the dependencies and extracted the files from wsl-vpnkit.tar.gz  the wsl-vpnkit.service file needs to be modified. Say you have placed wsl-vpnkit, wsl-vm, wsl-gvproxy.exe at /opt/app, the file should then be:
```
[Unit]
Description=wsl-vpnkit
After=network.target

[Service]
# for wsl-vpnkit setup as a distro
#ExecStart=/mnt/c/Windows/system32/wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit

# for wsl-vpnkit setup as a standalone script
ExecStart=/opt/app/wsl-vpnkit
Environment=VMEXEC_PATH=/opt/app/wsl-vm GVPROXY_PATH=/opt/app/wsl-gvproxy.exe

Restart=always
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

I agree that this isn't that obvious from the readme. Please note that I am a user like you all I can attest to is what worked for me.

**Comment by dpanici** [comment]
Got it, thanks yea I missed that I had to edit the paths. I appreciate the help!

**Comment by pradoz** [comment]
Where was VMEXEC_PATH=/opt/app/wsl-vm located? I'm only seeing a binary for wsl-gvproxy.exe

**Comment by r1m** [comment]
> Where was VMEXEC_PATH=/opt/app/wsl-vm located? I'm only seeing a binary for wsl-gvproxy.exe

From the tar /app content, https://github.com/sakai135/wsl-vpnkit?tab=readme-ov-file#setup-as-a-standalone-script
