### ISSUE TITLE
error `System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down.` when trying to run `sudo systemctl start wsl-vpnkit`

### ISSUE THREAD

**Issue by dpanici** [sakai135/wsl-vpnkit#224]
Hi,

Apologies for the likely naive questions, I am not super familiar with setting up processes/distros in linux or powershell.

I am following the instructions to setup systemd to run wsl-vpnkit, on WSL2 and I have Windows 10 as my main OS. 
I believe I have enabled systemd as when I run `systemctl list-unit-files --type=service` I see a list of services in `wsl2`. 

But when I run `sudo systemctl start wsl-vpnkit`,I receive the error `System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down.`

Maybe some clarification could be useful in the instructions. The complete procedure I did here was 
- follow setup as distro instructions
  - download the tar file
  - run `wsl --import wsl-vpnkit --version 2 $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz` in powershell
  - wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit
- at this point I have an open powershell with the wsl-vpnkit running (unsure if this is what I need to be doing at this point, it is not very clear, must the process always be running in the foreground?)
- download the [systemd file](https://github.com/sakai135/wsl-vpnkit/blob/v0.4.1/wsl-vpnkit.service) to my WSL2 using `curl`
- check that `systemd` is running by doing `systemctl list-unit-files --type=service`, which returned a list of services so it seems it is indeed running 
- follow the instructions in the box under [Setup systemd](https://github.com/sakai135/wsl-vpnkit#setup-systemd) exactly on my WSL2 terminal (with exception of using `vim` instead of `nano`)
- Get error described above when running `sudo systemctl start wsl-vpnkit`

Thanks in advance for the help!

**Comment by tomellis** [comment]
I had the same error, after following the instructions here: https://askubuntu.com/questions/1379425/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate I was able to resolve.

Specifically:
`wsl --update`

Add the lines to /etc/wsl.conf:
```
[boot]
systemd=true

```
Restart wsl:
`wsl --shutdown
`
Then opening up a new wsl session, I was able to successfully run the systemctl commands mentioned and the wsl-vpnkit service runs in the background.

**Comment by dpanici** [comment]
thanks, that worked!

Unfortunately, I seem to lose internet when I start the process which is the opposite of what I hoped would happen, but this at least solved the specific issue I was happening, so I'll close the issue
