### ISSUE TITLE
wsl.exe: 1: MZ: Permission denied

### ISSUE THREAD

**Issue by zcharym** [sakai135/wsl-vpnkit#228]
the issue comes after rebooting Windows today, Is anyone familiar with this `MZ` stuff?

distribution: `Ubuntu-22.04 `
WSL-version: `2`
booting with .zshrc config:
```bash
wsl.exe -d wsl-vpnkit --cd /app service wsl-vpnkit start
```

**Comment by r1m** [comment]
This fixed it for me : https://github.com/microsoft/WSL/issues/8952#issuecomment-1572193568
to run from your Ubuntu.
See https://github.com/sakai135/wsl-vpnkit/issues/217

**Comment by zcharym** [comment]
@r1m thanks a lot :)
