### ISSUE TITLE
wsl-vpnkit and wsl 2.0.14

### ISSUE THREAD

**Issue by blakeduffey** [sakai135/wsl-vpnkit#252]
wsl 2.0.14 has been released.  

This is supposed to resolve a recent issue running wsl-vnpkit as a systemd service (which emerged with wsl 2.0.5).  Per the release notes:

_Disable the 'NoRemoteImages' process mitigation policy since it breaks execution of windows executables (solves https://github.com/microsoft/WSL/issues/10812)_

I've upgraded to 2.014, installed a fresh Ubuntu instance and setup a new wsl-vpnkit (all fresh).  I'm following the same steps I've followed dozens of times prior.

When I run systemctl status wsl-vpnkit I get the following (please see attachment)
![wsl 2 0 14 error](https://github.com/sakai135/wsl-vpnkit/assets/5239758/3179490d-c734-4136-a2f8-9d8de4699a3f)

**Comment by blakeduffey** [comment]
Appears to be the same issue from https://github.com/sakai135/wsl-vpnkit/issues/234

**Comment by OrpheeGT** [comment]
https://github.com/sakai135/wsl-vpnkit/issues/249#issuecomment-1838796709

**Comment by blakeduffey** [comment]
I'm doing some additional testing to rule out some third party software impacting this.

**Comment by blakeduffey** [comment]
I believe 2.0.14 resolves the issue with wsl-vpnkit

**Comment by rs38** [comment]
not for me!
