### ISSUE TITLE
How to configure with multiple WSL distro?

### ISSUE THREAD

**Issue by philippe-granet** [sakai135/wsl-vpnkit#26]
I have to work with multiple WSL distro running at same time.
Is it possible to use your script with more than one distro running at same time?

**Comment by albertony** [comment]
Only one can run at a time, I think. At least you will have to configure different IP, named pipes etc..

What I do is to just run the vpnkit stuff from a single distro, and then other distros connects through the same by simply configuring them to go through the running vpnkit "nameserver":

/etc/wsl.conf:
```
[network]
generateResolvConf = false
```

/etc/resolv.conf:
```
nameserver 192.168.67.1
```
(may also add a second line with "nameserver 1.1.1.1" if you want this as fall-back).

A `wsl.exe --terminate <distroname>` or even `wsl.exe --shutdown`  is usually needed for the DNS configuration to be properly applied.

**Comment by sakai135** [comment]
It will work with multiple WSL 2 distros. With WSL 2, all the distros run within the same VM and [share the network namespace](https://github.com/microsoft/WSL/issues/4304). When you run `wsl-vpnkit`, you'll see that the `eth1` and the updated default route in `ip route` will show in both distros. The only thing left to do would be setting the DNS server as @albertony mentioned.

If you're using the `wsl-vpnkit.service` script, you would want to use your default distro to run this or edit the script to specify the distro in the `wsl.exe` command.

**Comment by philippe-granet** [comment]
Thank you for your explanations!
