### ISSUE TITLE
Problem using vpn kit on Alpine

### ISSUE THREAD

**Issue by andyneff** [sakai135/wsl-vpnkit#27]
I'm running into some problem using the WSL VPN Kit (running in Ubuntu-20.04 WSL2) from alpine in WSL2

## Steps to reproduce

1. Setup wsl-vpnkit in Ubuntu-20.04
2. Restart Ubuntu-20.04 and start wsl-vpnkit
    - Internet works in Ubuntu-20.04 while on VPN now 👍
3. Start alpine (3.13.4, if that matters. Installed from MS Store fresh today)
4. Edit `/etc/wsl.conf` just like I did in Ubuntu

    ```ini
    [network]
    generateResolvConf = false
    ```

5. Edit `/etc/resolv.conf` to read `nameserver 192.168.67.1`
6. Restart Alpine to make sure everything is happy.

## What doesn't work

Anything that needs dns resolution

- `ping www.google.com`
    - `ping: bad address 'www.google.com'`
- `wget http://www.example.com`
    - `wget: bad address 'www.example.com'`

I get the same failures both on and off of VPN

## What does work

DNS resolution and internet traffic actually both work

- `nslookup example.com`

    ```
    Server:         192.168.67.1
    Address:        192.168.67.1#53

    Non-authoritative answer:
    Name:   example.com
    Address: 93.184.216.34
    ** server can't find example.com: NXDOMAIN
    ```

- `wget http://45.33.7.16/`

    ```
    Connecting to 93.184.216.34 (93.184.216.34:80)
    wget: server returned error: HTTP/1.1 404 Not Found
    ```

- `ip route`

    ```
    default via 192.168.67.1 dev eth1
    172.22.224.0/20 dev eth0 scope link  src 172.22.226.58
    192.168.67.0/24 dev eth1 scope link  src 192.168.67.3
    ```

I get the same results both on and off of VPN

Additional: If I delete `/etc/wsl.conf` and `/etc/resolv.conf` and restart WSL while off of VPN, everything works as normal, but only when not on VPN. So alpine _is_ working when not using vpnkit

## What I expect

Internet should be working, especially if `wget` by IP and and `nslookup` are both clearly working. What could be going on to prevent this from functioning as intended?

**Comment by sakai135** [comment]
If you install `curl` in Alpine, does `curl http://www.example.com` work?

Which Alpine distro and what version of busybox are you using?

**Comment by andyneff** [comment]
Installing `curl` and using the (non-busybox version of) `curl` does indeed behave in the same way as `wget` mentioned in the OP. Bad address

Alpine Version: 3.13.4
Busybox Version: 1.32.1

**Comment by andyneff** [comment]
I was able to get things working without needing the `resolv.conf` file anymore, so now alpine is happy with that (100% pure routing solution). If I had to guess, alpine's invisible default for `nsswitch.conf` does not favor `resolv.conf` as some OSes are moving from resolv to resolve (with an e at the end). So I'll just go with I don't know what Alpine is doing, but it's probably not resolv, and everything works now with the pure routing solution ;)
