### ISSUE TITLE
Better solution?

### ISSUE THREAD

**Issue by meandmymind** [sakai135/wsl-vpnkit#28]
Hi! Thanks for your great job!

I was able to use this project but for some reason I had very slow dns lookups. `ping 8.8.8.8` goes ok (50ms), but `git clone github.com/some/repo` takes 10 second to just __start__ cloning.

So I looked at other solutions and found [this ](https://github.com/microsoft/WSL/issues/1350#issuecomment-844452775)that helped me. Basically it gets DNS server addresses from VPN internet adapter and writes it to `/etc/resolv.conf` (and restores original dns providers when out of vpn).

Are the vpn wsl problems solved by yours and theirs solutions exact same problems?

If so, yours is monstreously more hard to use. Shouldn't we redirect new users to more lightweight solutions?

**Comment by sakai135** [comment]
If switching DNS servers alone fixes your issue, your network connection in WSL 2 is not truly blocked, and you should use simpler solutions. VPNKit here is more of a last-resort solution that handles all kinds of cases. Docker created it for a reason.

I would add that using `wsl-vpnkit` does not cause any perceptible performance degradation in my situation.
