### ISSUE TITLE
wsl vpn kit being terminated upon docker starts

### ISSUE THREAD

**Issue by umamittapalli** [sakai135/wsl-vpnkit#29]
First of all thank you so much for this project, Sakai135!!

installed wsl vpn kit through the wrapper https://github.com/mbl-35/wsl-vpnkit. everything working good but upon starting docker, wsl vpn service getting broken with the below error.

```
Failed to read a packet header from host Error: 0. No error information
2021/06/24 12:56:58 open //./pipe/wsl-vpnkit: The system cannot find the file specified.
EOF reading from socket: closing

Failed to read hello from client
Failed to negotiate vmnet connection
2021/06/24 12:56:59 open //./pipe/wsl-vpnkit: The system cannot find the file specified.
EOF reading from socket: closing
```
is this a limitation of either of docker or wsl vpn kit only one runs at a time? if not, can you please guide me on fixing this?

Thanks in advance!!

**Comment by sakai135** [comment]
@umamittapalli Docker for Windows will look for any process named `vpnkit.exe` and kill it when it starts (#13). To get around this, I've changed my setup to rename it `wsl-vpnkit.exe` (#15). A similar workaround should work for you too.

**Comment by umamittapalli** [comment]
you are right on the spot! that worked perfectly. thank you very much @sakai135!!

one quick question.. as you see 3 processes of wsl-vpnkit and 2 processes of wsl-vpnkit.sock are running. Is this expected or duplicate processes running and I should clean them up?

`
$ ps aux | grep wsl-vpnkit
root     18158  0.0  0.0   2608  1732 pts/1    S    19:17   0:00 /bin/sh /sbin/wsl-vpnkit
root     18160  0.0  0.0   2608   112 pts/1    S    19:17   0:00 /bin/sh /sbin/wsl-vpnkit
root     18162  0.0  0.0   6964  1836 pts/1    S    19:17   0:00 socat UNIX-LISTEN:/var/run/wsl-vpnkit.sock,fork,umask=007 EXEC:/sbin/wsl-vpnkit-npiperelay -ep -s //./pipe/wsl-vpnkit,nofork
root     18165  0.0  0.0   2608   112 pts/1    S    19:17   0:00 /bin/sh /sbin/wsl-vpnkit
root     18170  0.0  0.0    804     4 pts/1    S    19:17   0:00 /tools/init /mnt/c/wsl-vpnkit/win/bin/wsl-vpnkit.exe --ethernet \\.\pipe\wsl-vpnkit --listen-backlog 32 --gateway-ip 192.168.67.1 --host-ip 192.168.67.2 --lowest-ip 192.168.67.3 --highest-ip 192.168.67.14
root     18175  0.0  0.0   2608   112 pts/1    S    19:17   0:00 /bin/sh /sbin/wsl-vpnkit
root     18177  0.0  0.0   2272     4 pts/1    S    19:17   0:00 /sbin/wsl-vpnkit-tap-vsockd --tap eth1 --path /var/run/wsl-vpnkit.sock
root     18178  0.0  0.0    804     4 pts/1    S    19:17   0:00 /tools/init /sbin/wsl-vpnkit-npiperelay -ep -s //./pipe/wsl-vpnkit
root     18179  0.0  0.0   2640    32 pts/1    Sl   19:17   0:00 /sbin/wsl-vpnkit-tap-vsockd --tap eth1 --path /var/run/wsl-vpnkit.sock
`

Thank you very much Sir for the invaluable project and for your immediate reply!!

**Comment by umamittapalli** [comment]
nevermind! understood by going through wsl-vpnkit script. 
thanks again!!
