### ISSUE TITLE
netdev group is not available in non-debian distribution

### ISSUE THREAD

**Issue by mryserb** [sakai135/wsl-vpnkit#3]
The netdev group (used for the socat command) is a debian only thing. This group doesn't appear to exist in fedora or other distros. I'm not sure which group to go for otherwise. I use systemd-network for now until I find a better one or maybe it's already the right one?

**Comment by sakai135** [comment]
You can just remove the `group`. It probably would make sense to make its own group and such to tighten down the permissions.

**Comment by sakai135** [comment]
Removed the `group` from the script.
