### ISSUE TITLE
PTR records not resolving

### ISSUE THREAD

**Issue by pstefka** [sakai135/wsl-vpnkit#31]
Seems like resolving PTR DNS records is not working from WSL2. DNS resolution works correctly though.

A from WSL2:
```
# nslookup host.example.com
Server:         192.168.67.1
Address:        192.168.67.1#53

Non-authoritative answer:
Name:   host.example.com
Address: 10.28.83.140
```

PTR from WSL2:
```
# nslookup 10.28.83.140
** server can't find 140.83.28.10.in-addr.arpa: NXDOMAIN
```

However, resolving from Windows host works correctly:
```
# nslookup 10.28.83.140
Server:  dns.example.com
Address:  10.2.90.1

Name:    host.example.com
Address:  10.28.83.140
```

**Comment by sakai135** [comment]
This is due to VPNKit not handling this case: https://github.com/docker/for-win/issues/10876

You could specify a different DNS server to use by editing the following line in the script.

```sh
echo "nameserver $VPNKIT_GATEWAY_IP" > /etc/resolv.conf
```

**Comment by pstefka** [comment]
You're right! By setting the nameserver in the resolv.conf to the upstream DNS of the windows host, everything works.  

It's a pity the DNS server changes when connecting to a VPN (which is pretty frequent). It would be much better if the default config using VPNKIT_GATEWAY_IP worked.

Hope the issue will be resolved on the docker side.. 

Thanks a lot Sakai!

**Comment by sakai135** [comment]
If your DNS server IP address is static, you could edit the script to prevent changes to `resolv.conf`. Then you can add your DNS server there. You could also specify a second public DNS server for fallback when not connected to the VPN.
