### ISSUE TITLE
./wsl-vpnkit not found

### ISSUE THREAD

**Issue by ckabut** [sakai135/wsl-vpnkit#4]
Hello,
sudo /.wsl-vpnkit is not working for me: command not found

I followed your instructions, and no clue about my issue

Thank you

**Comment by androidotai** [comment]
> Hello,
> sudo /.wsl-vpnkit is not working for me: command not found
> 
> I followed your instructions, and no clue about my issue
> 
> Thank you

I think you should clone this repo or copy the code from file wsl-vpnkit in this repo first.
And make sure you run right command. 

> 

>
