### ISSUE TITLE
Random failed with distro

### ISSUE THREAD

**Issue by philippe-granet** [sakai135/wsl-vpnkit#46]
I have to launch one, two or three times the disto for it to work on my laptop.
I think it is the bug in WSL you have already create:
https://github.com/microsoft/WSL/issues/6917

As a workaround, instead of calling this:
`wsl.exe -d wsl-vpnkit service wsl-vpnkit start`

I remove background option of `wsl-vpnkit.service` and keep wsl.exe process in background like this:
```bash
wsl.exe -d wsl-vpnkit sed -i '/--background/d' /app/distro/wsl-vpnkit.service
wsl.exe -d wsl-vpnkit sed -i '/--stdout/d' /app/distro/wsl-vpnkit.service
wsl.exe -d wsl-vpnkit sed -i '/--stderr/d' /app/distro/wsl-vpnkit.service
nohup sh -c "wsl.exe -d wsl-vpnkit service wsl-vpnkit start" 2>&1 </dev/null &
```

Have you a better solution?

**Comment by sakai135** [comment]
Do the logs have anything when you start the service and it doesn't work?
```
wsl.exe -d wsl-vpnkit cat /var/log/wsl-vpnkit.log
```
```
starting wsl-vpnkit
vpnkit.exe exists at /mnt/c/Users/username/wsl-vpnkit/wsl-vpnkit.exe
npiperelay.exe exists at /mnt/c/Users/username/wsl-vpnkit/npiperelay.exe
waiting for /var/run/wsl-vpnkit.sock ...
found /var/run/wsl-vpnkit.sock
waiting for eth1 ...
found eth1
ip: RTNETLINK answers: File exists
successfully created TAP device eth1
starting in connect mode with path=/var/run/wsl-vpnkit.sock and tap=eth1
2021/10/11 23:11:04 open //./pipe/wsl-vpnkit: The system cannot find the file specified.
EOF reading from socket: closing

Failed to read hello from client
Failed to negotiate vmnet connection
wsl-vpnkit.exe: [INFO] Setting handler to ignore all SIGPIPE signals
wsl-vpnkit.exe: [INFO] ...multiple logs here...
wsl-vpnkit.exe: [INFO] TCP/IP ready
wsl-vpnkit.exe: [INFO] TCP/IP stack connected
```
I would also like to see the `pstree` when it fails.
```
wsl.exe -d wsl-vpnkit pstree
```
```
init-+-init---wsl-vpnkit-+-wsl-vpnkit---socat---npiperelay.exe
     |                   |-wsl-vpnkit---wsl-vpnkit.exe
     |                   `-wsl-vpnkit---vpnkit-tap-vsoc---vpnkit-tap-vsoc---4*[{vpnkit-tap-vsoc}]
```

Also, if you want to run the script in the foreground for `nohup` you can just use the script directly without the service script.
```
wsl.exe -d wsl-vpnkit /app/wsl-vpnkit
```

**Comment by philippe-granet** [comment]
In order to keep process running, I use `daemonize` tool and launch this in my distro:
`daemonize $(which wsl.exe) -d wsl-vpnkit wsl-vpnkit`

**Comment by sakai135** [comment]
@philippe-granet do you still have this issue? Although if daemonize is working for you, that might be the best solution for now.
