### ISSUE TITLE
DNS resolution

### ISSUE THREAD

**Issue by tatroc** [sakai135/wsl-vpnkit#5]
I have wsl-vpnkit working as root user. However, I am facing one issue. Name resolution works as root user, but not as a non privileged user. I am using the wsl-vpnkit default gateway in the resolve.conf file per the instructions.

**Comment by sakai135** [comment]
Does it work for a normal user if you set a different DNS server like `1.1.1.1` in `/etc/resolv.conf`?

**Comment by u565620** [comment]
I tried several dns servers, 8.8.8.8 along with corporate dns servers. 
None of these worked except for. nameserver 192.168.67.1

As a normal user I can ping 8.8.8.8 and I can ping ips on corporate vpn. However, name lookups will not work as normal user.

**Comment by sakai135** [comment]
Try running `sudo nslookup example.com` and `nslookup example.com` multiple times. Do they use the same servers?

**Comment by tatroc** [comment]
silly mistake I had permissions 600 on /etc/resolv.conf . Thanks for the suggestions.
