### ISSUE TITLE
TUNSETIFF failed Error: 16. Resource busy

### ISSUE THREAD

**Issue by lumi017** [sakai135/wsl-vpnkit#6]
Getting the following failure when running the script, used to work before.
```
vpnkit.exe: [INFO] C:\Windows\System32\drivers\etc\hosts file has bindings for host.docker.internal gateway.docker.internal kubernetes.docker.internal
TUNSETIFF failed Error: 16. Resource busy
```

**Comment by lumi017** [comment]
Works after WSL restart. Any actions to do to unblock it without restart?

**Comment by sakai135** [comment]
When it happens, do you already have a network device with the name `eth1` when you run `ifconfig`? If you recognize the device, setting a different value for `TAP_NAME` in the script to avoid a conflict could help.

If you don't recognize the device or think it's a leftover from a previous run of wsl-vpnkit, you can try running `ifconfig eth1 down` to remove the device and see if that works.

**Comment by lumi017** [comment]
Thanks, good to know in case I reproduce.
