### ISSUE TITLE
Windows processes show as windows when running with WSL Preview 

### ISSUE THREAD

**Issue by sakai135** [sakai135/wsl-vpnkit#61]
When running the service with the WSL Preview 0.48.2.0 results in Windows executables showing up as separate windows. For now, the workaround is to run the script directly and keep the terminal open.

```
wsl.exe -d wsl-vpnkit wsl-vpnkit
```

https://github.com/microsoft/WSL/issues/7568

**Comment by bijancamp** [comment]
Thank you!

**Comment by sakai135** [comment]
v0.3.0 bypasses this by using `-H=windowsgui`
