### ISSUE TITLE
Fails if you have a space in username

### ISSUE THREAD

**Issue by miketweaver** [sakai135/wsl-vpnkit#71]
`wsl.exe -d wsl-vpnkit tail -f /var/log/wsl-vpnkit.log`
![image](https://user-images.githubusercontent.com/5581855/141059266-2803a6d5-ab7c-4a2f-960a-110d704d9198.png)

**Comment by sakai135** [comment]
Thanks, [v0.2.4](https://github.com/sakai135/wsl-vpnkit/releases/tag/v0.2.4) should resolve this issue.
