### ISSUE TITLE
Tried installing this but when I run it multiple console windows open

### ISSUE THREAD

**Issue by alexander-paterson** [sakai135/wsl-vpnkit#94]
I've got it installed, I can see it as an option in the Windows Terminal which when I open it shows some information on how to use it.

When in a powershell terminal I run `wsl.exe -d wsl-vpnkit service wsl-vpnkit start` a handful of terminal windows open, some have `[process exited with code 128 (0x00000080)]` in them, others are blank.

https://i.imgur.com/Y6CbQZM.png

If I try and close the terminal windows that are opened a seemingly endless number of them open one after another, I need to reboot my machine to get them to stop.

**Comment by sakai135** [comment]
Can you try v0.3.0 or run it in the foreground as in #61

**Comment by alexander-paterson** [comment]
v0.3.0 worked.
